quiz/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', home, name='home'),
    path('signup/', signup, name='signup'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    
    path('main/', main, name='main'),
    path('index/', index, name='index'),
    path('display/', display, name='display'),
    path('quiz/', quiz, name='quiz'),
    path('questions/<int:quizid>/',questions,name="questions"),
     path('questions/<int:quizid>/upload_to_ipfs/', upload_picture, name='upload_to_ipfs'),
    path('assigned_quiz/',assigned_quiz, name='assigned_quiz'),
    path('upload/<int:quizid>/', upload_picture, name='upload'),
    path('view_quiz/', view_quiz, name='view_quiz'),


    path('view_quiz_created/', view_quiz_created, name='view_quiz_created'),
    path('attempt_quiz/<str:quiz_id>/', attempt_quiz, name='attempt_quiz'),
    path('view_marks/<str:quiz_id>/', view_marks, name='view_marks'),
    path('save_marks/', save_marks, name='save_marks'),
    path('view_each_quiz/<str:quiz_id>/',view_each_quiz, name='view_each_quiz'),
     path('attempt_detail/<int:attempt_id>/', attempt_detail, name='attempt_detail'),
    
]

quiz_project/urls.py
# In urls.py of your project (e.g., quiz_project/urls.py)
from django.contrib import admin
from django.urls import path, include  # Import include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('quiz.urls')),  # Include the app's URL patterns
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

quiz/models.py
import random
import string
from django.contrib.auth.models import AbstractUser
from django.db import models

class CustomUser(AbstractUser):
    USER_TYPE_CHOICES = [
        ('Student', 'Student'),
        ('Teacher', 'Teacher'),
    ]

    user_type = models.CharField(max_length=10, choices=USER_TYPE_CHOICES)
    user_id = models.CharField(max_length=9, unique=True, primary_key=True)  # Length of 'user' + 4 digits

    def __str__(self):
         return f"{self.username} ({self.user_type}) - {self.user_id}"

    def save(self, *args, **kwargs):
        if not self.user_id:  
            self.user_id = 'user' + ''.join(random.choices(string.digits, k=4))
        super().save(*args, **kwargs)

class Quiz(models.Model):
    user= models.ForeignKey(CustomUser, on_delete=models.CASCADE) 
    quiz_name = models.CharField(max_length=200)
    quiz_id = models.CharField(max_length=9, unique=True, primary_key=True)  
    def __str__(self):
        return  f"{self.quiz_name} - {self.quiz_id}"

    def save(self, *args, **kwargs):
        if not self.quiz_id: 
            self.quiz_id = 'quiz' + ''.join(random.choices(string.digits, k=4))
        super().save(*args, **kwargs)

class Question(models.Model):
    question_id = models.CharField(max_length=9, unique=True, primary_key=True)  
    question_text = models.CharField(max_length=1000)
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)  
    question_marks = models.IntegerField(default=1)

    def __str__(self):
        return f"{self.question_text} - {self.quiz}"

    def save(self, *args, **kwargs):
        if not self.question_id: 
            self.question_id = f"{self.quiz.quiz_id}" + '-'.join(random.choices(string.digits, k=4))
        super().save(*args, **kwargs)

class Answer(models.Model):
    student = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    marks=models.IntegerField(default=0)
    answer_pic = models.ImageField(upload_to='answers')

class quiz_attempted(models.Model):
    quiz_attempt =  models.ForeignKey(Quiz, on_delete=models.CASCADE) 
    user_attempt= models.ForeignKey(CustomUser, on_delete=models.CASCADE)

class evaluated(models.Model):
    quiz_eval=models.ForeignKey(Quiz, on_delete=models.CASCADE) 
    user_eval=models.ForeignKey(CustomUser, on_delete=models.CASCADE)
  

quiz/forms.py
from django import forms
from .models import CustomUser
from django.contrib.auth.forms import UserCreationForm

class SignUpForm(UserCreationForm):
    user_type = forms.ChoiceField(choices=CustomUser.USER_TYPE_CHOICES)
    
    class Meta(UserCreationForm.Meta):
        model = CustomUser
        fields = ['username', 'user_type', 'password1', 'password2']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['password1'].widget = forms.PasswordInput(attrs={'placeholder': 'Password'})
        self.fields['password2'].widget = forms.PasswordInput(attrs={'placeholder': 'Confirm Password'})

    def save(self, commit=True):
        user = super().save(commit=False)
        if commit:
            user.save()
        return user


from django import forms

class PictureForm(forms.Form):
    picture = forms.ImageField()

quiz/views.py
from django.conf import settings
from django.shortcuts import get_object_or_404, render, redirect
from .forms import *
from .models import *
from django.contrib.auth import authenticate, login,logout
from django.contrib import messages
from web3 import Web3
from django.http import HttpResponse
from django.http import JsonResponse
from ipfshttpclient import connect
from django.views.decorators.csrf import csrf_exempt
from django.shortcuts import render
from django.http import HttpResponse
from .forms import PictureForm 
import os
import requests
from dotenv import load_dotenv


load_dotenv()


def upload_to_pinata(filepath, jwt_token):
    url = "https://api.pinata.cloud/pinning/pinFileToIPFS"
    headers = {'Authorization': f'Bearer {jwt_token}'}

    with open(filepath, 'rb') as file:
        response = requests.post(url, files={'file': file}, headers=headers)
        if response.status_code == 200:
            return response.json().get('IpfsHash')  # Return the IPFS hash
        else:
            return None  # Return None if upload fails
@csrf_exempt
def upload_picture(request,quizid):
    if request.method == 'POST':
        form = PictureForm(request.POST, request.FILES)
        if form.is_valid():
            print("lll")
            picture = form.cleaned_data['picture']
            # Assuming MEDIA_ROOT is where you store uploaded files
            file_path = os.path.join(settings.MEDIA_ROOT, picture.name)
            with open(file_path, 'wb') as f:
                for chunk in picture.chunks():
                    f.write(chunk)
            PINATA_JWT_TOKEN = os.getenv('PINATA_JWT_TOKEN')
            ipfs_hash = upload_to_pinata(file_path, PINATA_JWT_TOKEN)
            print(ipfs_hash)
            os.remove(file_path)
            if ipfs_hash:
                return JsonResponse({'success': True, 'ipfs_hash': ipfs_hash})
            else:
                return JsonResponse({'success': False, 'error': 'Failed to upload picture to Pinata'}, status=500)
    return  render(request, 'upload.html',{'quizid': quizid})


def index(request):
    return render(request, 'index.html')


def display(request):
    return render(request, 'display.html')

def questions(request,quizid):
    return render(request, 'questions.html', {'quizid': quizid})
    



def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('login')  # Redirect to login page after successful signup
    else:
        form = SignUpForm()
    return render(request, 'signup.html', {'form': form})




def login_view(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('main') 
        else:
            messages.error(request, 'Invalid username or password. Please try again.')
    return render(request, 'login.html')

def logout_view(request):
    logout(request)
    return redirect('home') 

def quiz(request):
    if request.method == 'POST':
        cur_user=request.user

        quiz_name = request.POST.get('quiz_name')
        question_texts = request.POST.getlist('question_text[]')
        question_marks = request.POST.getlist('question_marks[]')

        if quiz_name and question_texts and question_marks:
            quiz = Quiz.objects.create(quiz_name=quiz_name,user=cur_user)

            for text, marks in zip(question_texts, question_marks):
                Question.objects.create(question_text=text, quiz=quiz, question_marks=marks)

            return redirect('main')  

    return render(request, 'quiz.html')

def home(request):
    return render(request, 'home.html')

def main(request):
    return render(request, 'main.html')

def view_quiz(request):
    return render(request, 'view_quiz.html')

def assigned_quiz(request):
    quizzes = Quiz.objects.all()
    user = request.user
    attempted_quizzes = quiz_attempted.objects.filter(user_attempt=user).values_list('quiz_attempt', flat=True)
    return render(request, 'assigned_quiz.html', {'quizzes': quizzes, 'attempted_quizzes': attempted_quizzes})

def view_quiz_created(request):
    cur_user= request.user
    quizzes_created_by_user = Quiz.objects.filter(user=cur_user)
    print(quizzes_created_by_user)
    return render(request, 'view_quiz_created.html', {'quizzes': quizzes_created_by_user})

def view_each_quiz(request, quiz_id):
    quiz = get_object_or_404(Quiz, quiz_id=quiz_id)
    questions = Question.objects.filter(quiz=quiz)
    quiz_attempts = quiz_attempted.objects.filter(quiz_attempt=quiz)
    print("qqq",quiz_attempts)
    user_attempts = []
    for attempt in quiz_attempts:
        user = attempt.user_attempt
        print("user",user)
        attempt_id = attempt.id
        is_evaluated = evaluated.objects.filter(quiz_eval=quiz, user_eval=user)
        print("iss",is_evaluated)
        user_evaluation_status = "Evaluated" if is_evaluated else "Evaluate"
        user_attempts.append({'user': user, 'attempt_id': attempt_id, 'evaluation_status': user_evaluation_status})
        print(user_attempts)

    context = {
        'quiz': quiz,
        'questions': questions,
        'user_attempts': user_attempts
    }
 
    return render(request, 'view_each_quiz.html', context)
       


def attempt_quiz(request, quiz_id):
    quiz = Quiz.objects.get(quiz_id=quiz_id)
    questions = Question.objects.filter(quiz=quiz)

    if request.method == 'POST':
        answers = []
        for question in questions:
            answer_pic = request.FILES.get(f'answer_{question.question_id}') 
            if answer_pic:
                answers.append(Answer(student=request.user, question=question, answer_pic=answer_pic))
            else:
                messages.error(request, f'Answer for question "{question.question_text}" is missing.')
              
        if answers:
            Answer.objects.bulk_create(answers)
            quiz_attempted.objects.create(quiz_attempt=quiz, user_attempt=request.user)
            messages.success(request, 'Your answers have been submitted successfully!')
            return redirect('main')

    return render(request, 'attempt_quiz.html', {'quiz': quiz, 'questions': questions})

def attempt_detail(request, attempt_id):
    attempt = get_object_or_404(quiz_attempted, id=attempt_id)
    user_attempt = attempt.user_attempt
    quiz = attempt.quiz_attempt
    questions = Question.objects.filter(quiz=quiz)
    answers = Answer.objects.filter(student=user_attempt, question__quiz=quiz)
    print(answers)
    return render(request, 'attempt_detail.html', {'user_attempt': user_attempt, 'quiz': quiz, 'questions': questions, 'answers': answers})

def save_marks(request):
    if request.method == 'POST':
       
        for answer in Answer.objects.all():
            marks_field_name = 'marks_' + str(answer.id)
            if marks_field_name in request.POST:
                marks = int(request.POST[marks_field_name])
                answer.marks = marks
                answer.save()
        evaluated.objects.create( quiz_eval=answer.question.quiz,user_eval=answer.student)
        return render(request, 'main.html')
    else:
        
        pass
def view_marks(request,quiz_id):
  
    current_user = request.user
    quiz_questions = Question.objects.filter(quiz=quiz_id)
    question_marks = {}

    for question in quiz_questions:

        answer = Answer.objects.get(student=current_user, question=question)
        question_marks[question.question_text] = answer.marks
       

    context = {
        'question_marks': question_marks
    }
    return render(request, 'view_marks.html', context)

quiz/templates/assigned_quiz.html
{% load static %}

<!DOCTYPE html>

<html>
<head>
    <title>All Quizzes</title>
    <link rel="stylesheet" href="{% static 'css/view_quiz.css' %}">

</head>
<body>
    
    <div id="quizzes">
    </div>
    

    <script src="https://cdn.jsdelivr.net/npm/web3@1.7.0/dist/web3.min.js"></script>
    <script>
        // Connect to the Ethereum network
        if (window.ethereum) {
            window.web3 = new Web3(window.ethereum);
            window.ethereum.enable();
        } else {
            console.error('No Ethereum provider detected. Install MetaMask or another wallet.');
        }

        // Contract ABI and Address
        const contractABI = [
            {
                "constant": true,
                "inputs": [],
                "name": "getAllQuizzes",
                "outputs": [
                    {"name": "", "type": "string[]"},
                    {"name": "", "type": "uint256[]"}
                ],
                "payable": false,
                "stateMutability": "view",
                "type": "function"
            }
        ];

        const contractAddress = '0xDcBB5A881394e0F4E5370967Cfd44C479041F2d0'; // Replace with your contract's address
        const contract = new web3.eth.Contract(contractABI, contractAddress);

        async function getAllQuizzes() {
            try {
                const quizzes = await contract.methods.getAllQuizzes().call();
                
                let quizzesHTML = '<h1>Quiz</h1>';
                for (let i = 0; i < quizzes[0].length; i++) {
                    var quizId = quizzes[1][i];
                    var url = "{% url 'questions' quizid=12345 %}".replace('12345', quizId);
                    quizzesHTML += `<div class="quiz"><span>Quiz ID : ${quizId}</span><a href="${url}"><span>Name :</span>${quizzes[0][i]}</a></div>`;
                }
                document.getElementById('quizzes').innerHTML = quizzesHTML;
            } catch (error) {
                console.error("Error fetching quizzes:", error);
            }
        }

        getAllQuizzes();
    </script>
</body>
</html>

quiz/templates/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home</title>
    <link rel="stylesheet" href="{% static 'css/home.css' %}">

</head>
<body>
   
   
    <h1>Welcome</h1>
    <a href="{% url 'login' %}"><button>Login</button></a><br><br>
    <a href="{% url 'signup' %}"><button>Signup</button> </a>


</body>
</html>

quiz/templates/login.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <title>Login</title>
    <link rel="stylesheet" href="{% static 'css/login.css' %}">

</head>
<body>
    <h2>Login</h2>
    <form method="post" action="{% url 'login' %}">
        {% csrf_token %}
        <label for="username">Username:</label>
        <input type="text" id="username" name="username" required><br><br>
        <label for="password">Password:</label>
        <input type="password" id="password" name="password" required><br><br>
        <button type="submit">Login</button>
    </form>
</body>
</html>

quiz/templates/main.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body> 
    {% block sidebar %}
        {% include 'sidebar.html' %}
    {% endblock %}

    {% if user.user_type == 'teacher' %}

    {% block view_quiz %}
        {% include 'view_quiz.html' %}
    {% endblock %}

    {%else%}
    {% block assigned_quiz %}
    {% include 'assigned_quiz.html' %}

   
{% endblock %}
{%endif%}

    
</body>
</html>

quiz/templates/questions.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>Quiz Questions</title>
    <script src="https://cdn.jsdelivr.net/npm/web3@1.7.0/dist/web3.min.js"></script>
    <link rel="stylesheet" href="{% static 'css/questions.css' %}">

</head>
<body>
    <h1>Quiz Questions</h1>
    
    <!-- Display quiz ID -->
    <h3 class="qid">Quiz ID: {{quizid}}</h3>
    
    <!-- Container to display questions -->
    <div id="questions"></div>

    <script>
        // Connect to the Ethereum network
        if (window.ethereum) {
            window.web3 = new Web3(window.ethereum);
            window.ethereum.enable();
        } else {
            console.error('No Ethereum provider detected. Install MetaMask or another wallet.');
        }

        // Contract ABI and Address
        const contractABI = [
            {
                "constant": true,
                "inputs": [{"name": "_quizId", "type": "uint256"}],
                "name": "getQuiz",
                "outputs": [
                    {"name": "quizName", "type": "string"},
                    {"name": "questionCount", "type": "uint256"}
                ],
                "payable": false,
                "stateMutability": "view",
                "type": "function"
            },
            {
                "constant": true,
                "inputs": [
                    {"name": "_quizId", "type": "uint256"},
                    {"name": "_questionId", "type": "uint256"}
                ],
                "name": "getQuestion",
                "outputs": [
                    {"name": "text", "type": "string"},
                    {"name": "assignedMarks", "type": "uint256"}
                ],
                "payable": false,
                "stateMutability": "view",
                "type": "function"
            },
            {
                "constant": false,
                "inputs": [
                    {"name": "_quizId", "type": "uint256"},
                    {"name": "_questionId", "type": "uint256"},
                    {"name": "_imageCid", "type": "string"}
                ],
                "name": "submitAnswer",
                "outputs": [],
                "payable": false,
                "stateMutability": "nonpayable",
                "type": "function"
            }
        ];
        const quizId = "{{quizid}}";
        const contractAddress = '0xDcBB5A881394e0F4E5370967Cfd44C479041F2d0'; // Replace with your contract's address
        const contract = new web3.eth.Contract(contractABI, contractAddress);

        async function getQuizQuestions() {
            // Remove defining quizId here
        
            try {
                const quiz = await contract.methods.getQuiz(quizId).call();
                const questionCount = quiz.questionCount;
                let questionsHTML = `<h3>Quiz name : ${quiz.quizName} </h3>`;
                for (let i = 0; i < questionCount; i++) {
                    const question = await contract.methods.getQuestion(quizId, i).call();
                    questionsHTML += `
                        <div>
                            <h4>Question ${i+1}: ${question.text} (Marks: ${question.assignedMarks})</h4>
        
                            <form class="uploadForm" enctype="multipart/form-data" data-question-id="${i}">
                                {% csrf_token %}
                                <input type="file" name="picture" accept="image/*" required>
                                <button type="submit">Upload</button>
                                <div><h4 class="result"></h4></div>
                            </form>
                        </div>
                    `;
                }
                document.getElementById('questions').innerHTML = questionsHTML;
                
                document.querySelectorAll('.uploadForm').forEach(form => {
                    form.addEventListener('submit', function(event) {
                        event.preventDefault();
                        var formData = new FormData(this);
                        var questionId = this.dataset.questionId;
                        fetch(`/questions/${quizId}/upload_to_ipfs/`, {
                            method: 'POST',
                            headers: {
                                'X-CSRFToken': document.querySelector('[name=csrfmiddlewaretoken]').value
                            },
                            body: formData,
                        })
                        .then(response => {
                            if (!response.ok) {
                                throw new Error('Network response was not ok');
                            }
                            return response.json();
                        })
                        .then(data => {
                            if (data.success) {
                                var ipfsHash = data.ipfs_hash;
                                submitAnswer(quizId, questionId, ipfsHash);
                                this.querySelector('.result').innerHTML = `Picture uploaded successfully to Pinata! IPFS hash: ${ipfsHash}`;
                            } else {
                                // Display error message
                                this.querySelector('.result').textContent = `Error: ${data.error}`;
                            }
                        })
                        .catch(error => {
                            // Display fetch error
                            this.querySelector('.result').textContent = `Fetch error: ${error.message}`;
                        });
                    });
                });
            } catch (error) {
                console.error("Error fetching quiz questions:", error);
            }
        }
        

        
        async function submitAnswer(quizId, questionId, imageCid) {
            try {
                // Get user account
                const accounts = await window.web3.eth.getAccounts();
                const userAccount = accounts[0];
        
                // Contract instance
                const contract = new window.web3.eth.Contract(contractABI, contractAddress);
        
                // Call the submitAnswer function
                await contract.methods.submitAnswer(quizId, questionId, imageCid).send({ from: userAccount });
        
                console.log("Answer submitted successfully!");
            } catch (error) {
                console.error("Error submitting answer:", error);
            }
        }

        getQuizQuestions();
    </script>
</body>
</html>

quiz/templates/quiz.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <title>Quiz DApp</title>
    <script src="https://cdn.jsdelivr.net/npm/web3@1.7.0/dist/web3.min.js"></script>
    <link rel="stylesheet" href="{% static 'css/quiz.css' %}">

</head>
<body>
    
    
    <h2>Create Quiz</h2>
    <form id="quizForm">
        <label for="quizName">Quiz Name:</label>
        <input type="text" id="quizName" name="quizName"><br>
        <button type="button" onclick="createQuiz()">Create Quiz</button>
    </form>
    
    <h2>Add Question</h2>
    
    <form id="questionForm">
        <!-- No need to input Quiz ID -->
        <label for="questionText">Question Text:</label>
        <input type="text" id="questionText" name="questionText">
        <label for="assignedMarks">Assigned Marks:</label>
        <input type="number" id="assignedMarks" name="assignedMarks"><br>
        <button type="button" onclick="addQuestion()">Add Question</button>
    </form>

    <script src="{% static 'js/quiz.js' %}"></script>
</body>
</html>

quiz/templates/sidebar.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home</title>
    <link rel="stylesheet" href="{% static 'css/sidebar.css' %}">
</head>
<body>
    <div class="sidebar">
        <div class="user-info">
            <p id="username">Username: {{ user.username }}</p>
            <p id="user_type">{{ user.user_type }}</p>
        </div>
        <ul class="menu"> 
            {% if user.user_type == 'teacher' %}
            <li><a href="{% url 'quiz' %}" id="create-quiz-link">Create Quiz</a></li>
        
            {% endif %}
            <li><a href="{% url 'logout' %}" id="logout-link">Logout</a></li>
        </ul>
    </div>
   
    
</body>
</html>

quiz/templates/signup.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <title>Sign Up</title>
    <link rel="stylesheet" href="{% static 'css/signup.css' %}">
</head>
<body>
    <h2>Sign Up</h2>
    <form method="post" action="{% url 'signup' %}">  <!-- Specify action attribute -->
        {% csrf_token %}
        <div>
            <label for="id_username">Username:</label>
            {{ form.username }}
           
        </div>
        <div>
            <label for="id_user_type">User Type:</label>
            {{ form.user_type }}
            <!-- You can customize error output here if needed -->
        </div>
        <div>
            <label for="id_password1">Password:</label>
            {{ form.password1 }}
            <!-- You can customize error output here if needed -->
        </div>
        <div>
            <label for="id_password2">Confirm Password:</label>
            {{ form.password2 }}
            <!-- You can customize error output here if needed -->
        </div>
        <button type="submit">Sign Up</button>
    </form>
</body>
</html>

quiz/templates/view_quiz.html
{% load static %}

<!DOCTYPE html>

<html>
<head>
    <title>All Quizzes</title>
    <link rel="stylesheet" href="{% static 'css/view_quiz.css' %}">

</head>
<body>
    
    <div id="quizzes">
    </div>
    

    <script src="https://cdn.jsdelivr.net/npm/web3@1.7.0/dist/web3.min.js"></script>
    <script>
        // Connect to the Ethereum network
        if (window.ethereum) {
            window.web3 = new Web3(window.ethereum);
            window.ethereum.enable();
        } else {
            console.error('No Ethereum provider detected. Install MetaMask or another wallet.');
        }

        // Contract ABI and Address
        const contractABI = [
            {
                "constant": true,
                "inputs": [],
                "name": "getAllQuizzes",
                "outputs": [
                    {"name": "", "type": "string[]"},
                    {"name": "", "type": "uint256[]"}
                ],
                "payable": false,
                "stateMutability": "view",
                "type": "function"
            }
        ];

        const contractAddress = '0xDcBB5A881394e0F4E5370967Cfd44C479041F2d0'; // Replace with your contract's address
        const contract = new web3.eth.Contract(contractABI, contractAddress);

        async function getAllQuizzes() {
            try {
                const quizzes = await contract.methods.getAllQuizzes().call();
                
                let quizzesHTML = '<h1>Quiz</h1>';
                for (let i = 0; i < quizzes[0].length; i++) {
                    var quizId = quizzes[1][i];
                    var url = "{% url 'upload' quizid=12345 %}".replace('12345', quizId);
                    quizzesHTML += `<div class="quiz"><span>Quiz ID : ${quizId}</span><a href="${url}"><span>Name :</span>${quizzes[0][i]}</a></div>`;
                }
                document.getElementById('quizzes').innerHTML = quizzesHTML;
            } catch (error) {
                console.error("Error fetching quizzes:", error);
            }
        }

        getAllQuizzes();
    </script>
</body>
</html>